function ForceandTorques = OpenMan_torquesandforce(b1,b4,theta2,theta3)
%OpenMan_torquesandforce
%    ForceandTorques = OpenMan_torquesandforce(B1,B4,THETA2,THETA3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    23-May-2024 05:57:54

ForceandTorques = [b1;theta2;theta3;b4];
